### ISSUE TITLE
"stream_records" does not exist on production

### ISSUE THREAD

**Issue by valexl** [zilverline/sequent#375]
I've faced with a very weird issue. Time to time the app can't handle the requests and raises this error:

`ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "stream_records" does not exist
LINE 1: SELECT 1 AS one FROM "stream_records" WHERE "stream_records".`

It looks like something random. One request is handled without any problem. The next one can raise this error. Then next attempt works well again. My main assumption right now is the order in `schema_search_path`. But I can see in your examples that you force the order here - https://github.com/zilverline/sequent-examples/commit/a5dcab9e9db1f66b762f013a95e2477492a12fc5. Not sure how to fix that.

here is `database.yml`

```
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>
  advisory_locks: <%= ENV.fetch("MIGRATION_ADVISORY_LOCKS", true) %>
  prepared_statements: <%= ENV.fetch("ENABLE_PREPARED_STATEMENTS", true) %>
  schema_search_path: "<%= ENV['SEQUENT_MIGRATION_SCHEMAS'] || 'public, sequent_schema, view_schema' %>"

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
```

I am using rails `rails (7.0.4.3)`, `sequent (6.0.0)` and ruby `3.2.2`.
