### ISSUE TITLE
Can't access right schema while running migrations in production

### ISSUE THREAD

**Issue by GabrielaGuedes** [zilverline/sequent#414]
Hi! I've created a new sequent migration and runned it in development environment without issues. However, after deploying the code and trying to run `bundle exec rake sequent:migrate:online` in production, it seems like sequent is accessing the `public` schema of my database instead of the `view_schema` one, throwing me the following error:

```
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "sequent_versions" does not exist (ActiveRecord::StatementInvalid)
LINE 1: SELECT "sequent_versions".* FROM "sequent_versions" ORDER BY...
```

The eager_loading is already set as true.

In the `database.yml`, the only difference between these two environments is that on development, we have the database connection set with the fields `database`, `username`, `password`, and `host`, and on production, we have set the `url`. 
Since we already had this problem in the past, when we had our fields set individually instead of grouped on the `url`, we tried different variations of config for the database (as listed below), but none of them was successful.

### 1. Setting just the `url` field on `database.yml`
Like mentioned above
### 2. Setting `database`, `username`, `password`, and `host` instead of using the `url`
Then, we run `bundle exec rake sequent:migrate:online`. However, it throws the same error as item 1 (missing sequent_versions)
### 3. Setting both the `url` and `database` + `username` + `password` fields on `database.yml`
After running `bundle exec rake sequent:migrate:online`, it throws the same error as item 1 (missing sequent_versions)
### 4. Running the migration inside the rails console with loaded db_config
To do so, a code like this was run:
```ruby
ENV['SEQUENT_ENV'] = ENV['RAILS_ENV']
db_config = Sequent::Support::Database.read_config(ENV['SEQUENT_ENV'])
view_schema = Sequent::Migrations::ViewSchema.new(db_config: db_config)

view_schema.send(:in_view_schema) do
  pp view_schema.exec_sql("SELECT current_schema();").to_a
end # => [{"current_schema"=>"public"}]

view_schema.migrate_online
```

But, when migrating, it throws an error saying that event_records does not exist:
```
I, [2024-05-15T14:05:16.418775 #2136]  INFO -- : group_exponent: 3
I, [2024-05-15T14:05:16.418926 #2136]  INFO -- : Start replaying events
I, [2024-05-15T14:05:16.420386 #2136]  INFO -- : Number of groups 4096
E, [2024-05-15T14:05:16.543767 #5083] ERROR -- : Replaying failed for ids: ^002 - 002
E, [2024-05-15T14:05:16.543837 #5083] ERROR -- : +++++++++++++++ ERROR +++++++++++++++
E, [2024-05-15T14:05:16.543922 #5083] ERROR -- : PG::UndefinedTable: ERROR:  relation "event_records" does not exist
LINE 10:  WHERE a.attrelid = '"event_records"'::regclass
```
### 5. Running the migration inside the rails console with manual set db_config
Very similar to the previous approach, but with the difference that now we are manually defining what needs to be the db_config
```ruby
db_config = {"primary"=>
{"adapter"=>"postgresql",
 "encoding"=>"unicode",
 "pool"=>15,
 "schema_search_path"=>"public,sequent_schema, view_schema",
 "variables"=>{"statement_timeout"=>"500s", "lock_timeout"=>"100s"},
 "database"=>"<our_db_name>",
 "username"=>"<our_db_user>",
 "password"=>"<our_db_password>", 
 "host"=>"<our_db_host>"},
"primary_replica"=>
{"replica"=>true,
 "adapter"=>"postgresql",
 "encoding"=>"unicode",
 "pool"=>15,
 "schema_search_path"=>"public,sequent_schema, view_schema",
 "variables"=>{"statement_timeout"=>"500s", "lock_timeout"=>"100s"},
 "database"=>"<our_replica_name>",
 "username"=>"<our_replica_user>",
 "password"=>"<our_replica_password>", 
 "host"=>"<our_replica_host>"}}
```
This keeps accessing the `public` schema and throwing the same error as item 4.
### 6. Running the migration inside the rails console with manual set db_config and without the `public` schema
The db_config is almost the same, being the only difference on the `schema_search_path` where we've put only `sequent_schema, view_schema`. However, this throws the same error as item 4.

## Versions
Rails 7.1.3.2
Sequent 7.0

## Files
database.yml
```
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  schema_search_path: "public, sequent_schema, view_schema"
  variables:
    statement_timeout: "500s"
    lock_timeout: "100s"

development:
  primary:
    <<: *default
    database: <our_db>
    username: <our_user>
    password: <our_password>
    host: <our_host>
    gssencmode: disable
  primary_replica:
    replica: true
    <<: *default
    database: <our_db>
    username: <our_user>
    password: <our_password>
    host: <our_host>
    gssencmode: disable

test:
  primary:
    <<: *default
    database: <our_db>
    username: <our_user>
    password: <our_password>
    host: <our_host>
    gssencmode: disable
  primary_replica:
    replica: true
    <<: *default
    database: <our_db>
    username: <our_user>
    password: <our_password>
    host: <our_host>
    gssencmode: disable

production:
  primary:
    <<: *default
    url: <our_url>
  primary_replica:
    replica: true
    <<: *default
    url: <our_url>

```

## References
- https://github.com/zilverline/sequent/issues/283
- https://github.com/zilverline/sequent/issues/205
